version: '3'
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${path_local_work}:/opt/adguardhome/work
      - ${path_local_conf}:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8088:80/tcp"
      - "3000:3000/tcp"
    deploy:
      resources:
          limits:
            cpus: 1.00
            memory: 512M
          reservations:
            cpus: 0.25
            memory: 256M
